awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=30

bar:
  height: 54
  location: top
  font: FiraCode:pixelsize=30
  background: 282c34ff
  foreground: abb2bfff
  margin: 20

  right:
    - battery:
        name: BAT0
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff, font: *awesome}
                      - string: {text: , foreground: ffa600ff, font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: " ", margin: 20}  # Adds space between the ramp and text
                - string: {text: "{capacity}% {estimate}"}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% {estimate}"}
              state == full:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% full"}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:   , foreground: ff0000ff, font: *awesome}
                      - string: {text:   , foreground: ffa600ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                      - string: {text:   , foreground: 00ff00ff, font: *awesome}
                - string: {text: " ", margin: 20}  # Adds space between the ramp and text
                - string: {text: "{capacity}%"}
  center:
    - clock:
        time-format: "%H:%M"
        content:
        - string: {text: "{date}", right-margin: 20}
        - string: {text: "{time}"}

